apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2-deployment
  labels:
    app: service2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service2
  template:
    metadata:
      labels:
        app: service2
    spec:  
      containers:
        - name: service2
          image: my-registry:5000/envoy-service2
          volumeMounts:
            - mountPath: "/etc"
              name: pv-storage
          ports:
            - containerPort: 80
          env:
            - name: SERVICE_NAME
              value: "2"
      volumes:
        - name: pv-storage
          persistentVolumeClaim:
            claimName: pv-claim        
